export const CORE_ACTIONS = {
  LOADING: 'LOADING',
  LOADED: 'LOADED',
};

export const UI_ACTIONS = {
  OPEN_DRAWER: 'OPEN_DRAWER',
  CLOSE_DRAWER: 'CLOSE_DRAWER',
  CHANGE_SCREEN: 'CHANGE_SCREEN',
  CHANGE_TITLE: 'CHANGE_TITLE',
};

export const NATIONS_ACTIONS = {
  SET_CURRENT_NATION: 'SET_CURRENT_NATION',
};
