export const CORE_ACTIONS = {
  LOADING: 'LOADING',
  LOADED: 'LOADED',
};

export const UI_ACTIONS = {
  OPEN_DRAWER: 'OPEN_DRAWER',
  CLOSE_DRAWER: 'CLOSE_DRAWER',
  CHANGE_SCREEN: 'CHANGE_SCREEN',
};
