export const APP_STATUS = {
  INACTIVE: 'INACTIVE',
  RUNNING: 'RUNNING',
  STARTING: 'STARTING',
  BROKEN: 'BROKEN',
};

export const SCREEN_TYPES = {
  LUCY: 'LUCY',
  CHAT: 'CHAT',
  NATIONS: 'NATIONS',
  PROFILE: 'PROFILE',
  WALLET: 'WALLET',
};
