export const APP_STATUS = {
  INACTIVE: 'INACTIVE',
  RUNNING: 'RUNNING',
  STARTING: 'STARTING',
  BROKEN: 'BROKEN',
};

export const SCREEN_TYPES = {
  WELCOME: 'WELCOME',
  MAIN: 'MAIN',
  NATIONS: 'NATIONS',
  NATION: 'NATION',
  SIGN_UP: 'SIGN_UP',
  LOGIN: 'LOGIN',
  ACCOUNT: 'ACCOUNT',
  LOADING: 'LOADING',
};
